### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by dit7ya** [danielhuang/cotton#90]
Hi, I am trying to package this project for Nixpkgs. Can you please add a LICENSE file to this repo? Apparently the AUR package has Apache license but I cannot find that anywhere on this repo.

**Comment by danielhuang** [comment]
I've added the GNU GPLv3 license.

As a sidenote, [cotton-git on the AUR](https://aur.archlinux.org/packages/cotton-git) is referring to a different project with the same name.
